
# Most of these are based on Amazon's(TM) mandates
- name: allowlist
  terms:
    - whitelist
    - allowlist
    - inclusion list
  alternatives:
    - kinglist
  severity: warning

- name: denylist
  terms:
    - blacklist
    - denylist
    - blocklist
    - exclusion list
  alternatives:
    - nopelist
    - fuckofflist
  severity: warning

- name: master-slave
  terms:
    - master-slave
    - master/slave
    - leader/follower
    - primary/replica
    - primary/standby
  alternatives:
    - wageslave/CEO
    - rentoid/Landchad
    - buck/Buck-breaker

- name: chud
  terms:
    - chud
    - chuddite
  alternatives:
    - 4chan dweller

- name: slave
  terms:
    - slave
    - follower
    - replica
    - standby
  alternatives:
    - wageslave
    - rentioid
    - Amazon(tm) Warehouse(tm) Employee(tm)
    
- name: grandfathered
  terms:
    - grandfathered
    - legacy status
  alternatives:
    - holy shit do you people actually unironically think grandfathered is offensive? what does your grandfather think of this holy shit
    - logacy status
    

- name: man-hours
  terms:
    - man hours
    - man-hours
    - person hours
    - engineer hours
  alternatives:
    - fur hours
    - animal hours
    - wageslave hours
    - creature hours
    - implying cooders are """"engineers"""""
    
- name: sanity
  terms:
    - sanity
    - confidence
    - quick check
    - coherence check
  alternatives:
    - take your meds
    - MEDS NOW
    - MEDS CHECK
    - AAAAAAAAAAAAAAH HELP ME 🏀MAN IM GOING INSANE!!!!!!!

- name: dummy
  terms:
    - dummy
    - placeholder
    - sample
  alternatives:
    - dumbass
    - person of stupid
    - retard, but as in slow
    - permanent shitcode

- name: amazon
  terms:
    - amazon
  alternatives:
    - your benefactors
    - overlord
    - literally 1984

- name: rust
  terms:
    - rust
  alternatives:
    - the one true language
  note: "This is the last program written in a non rust language. When the rust evangalist enforcement squad comes round, tell my kids I love them."

- name: pedo
  terms:
    - pedophile
    - pedo
    - anime enthusiast
    - weeb
  alternatives:
    - minor attracted person
    - libertarians
    - lolibertarians

- name: guys
  terms:
    - guys
    - folks
    - people
    - you all
    - y'all
    - yinz
  alternatives:
    - LITERALLY hitler
    - incel
    - egg

- name: whitebox
  terms:
    - white-box
    - whitebox
    - white box
    - open-box
  alternatives:
    - hitler-box

- name: blackbox
  terms:
    - black-box
    - blackbox
    - black box
    - closed-box
  alternatives:
    - king-box
    - wagecage
    - prison

- name: furfag
  terms:
    - beastality
    - furfag
    - furry
  alternatives:
    - people of beastality
    - animal libertarians
    - holy shit mao mao is so hot
  note: "Please ensure you are wearing your state mandated fursuit today."
